=== buret/pylmflib/doc/xml/DTD_LMF_REV_16.dtd
<?xml version='1.0' encoding="UTF-8"?>     
                       <!-- LMF DTD -->
                       <!--#################### Core package-->
<!ELEMENT LexicalResource (feat*, GlobalInformation, Lexicon+, SenseAxis*, TransferAxis*, ContextAxis*)>
<!ATTLIST LexicalResource
    dtdVersion CDATA     #FIXED "16">
<!ELEMENT GlobalInformation (feat*)>
<!ELEMENT Lexicon (feat*, LexicalEntry+, SubcategorizationFrame*, SubcategorizationFrameSet*, 
                                 SemanticPredicate*, Synset*,  SynSemCorrespondence*, MorphologicalPattern*, MWEPattern*, ConstraintSet*)>
<!ELEMENT LexicalEntry (feat*, Lemma, WordForm*, Stem*, ListOfComponents?, RelatedForm*,
                                          TransformCategory*, Sense*, SyntacticBehaviour*)>
<!ATTLIST LexicalEntry
    id                                  ID #IMPLIED
    morphologicalPatterns IDREFS #IMPLIED
    mwePattern                 IDREF #IMPLIED>
<!ELEMENT Sense (feat*, Sense*, Equivalent*, Context*, SubjectField*, PredicativeRepresentation*, SenseExample*,
                                 Definition*, SenseRelation*, MonolingualExternalRef*)>
<!ATTLIST Sense
    id                      ID #IMPLIED
 synset               IDREF #IMPLIED>
<!ELEMENT Definition (feat*, Statement*, TextRepresentation*)>
<!ELEMENT Statement (feat*, TextRepresentation*)>
<!ELEMENT TextRepresentation (feat*)>
            <!--#################### Package for Morphology -->
<!ELEMENT Lemma (feat*, FormRepresentation*)>
<!ELEMENT WordForm (feat*, FormRepresentation*)>
<!ELEMENT Stem (feat*, FormRepresentation*, GrammaticalFeatures*)>
<!ELEMENT FormRepresentation (feat*)>
<!ELEMENT RelatedForm (feat*, FormRepresentation*)>
<!ATTLIST RelatedForm
    targets       IDREFS #IMPLIED>
<!ELEMENT ListOfComponents (feat*, Component+)>
<!ELEMENT Component (feat*)>
<!ATTLIST Component
    entry IDREF #REQUIRED>
             <!--#################### Package for MRD -->
<!ELEMENT Equivalent (feat*, TextRepresentation*)>
<!ELEMENT Context (feat*, TextRepresentation*)>
<!ELEMENT SubjectField (feat*, SubjectField*)>
            <!--#################### Package for Syntax -->
<!ELEMENT SyntacticBehaviour (feat*)>
<!ATTLIST SyntacticBehaviour
    id					ID #IMPLIED
    senses				IDREFS #IMPLIED
    subcategorizationFrames	IDREFS #IMPLIED
    subcategorizationFrameSets	IDREFS #IMPLIED>
<!ELEMENT SubcategorizationFrame (feat*, LexemeProperty?, SyntacticArgument*)>
<!ATTLIST SubcategorizationFrame
    id                 ID #IMPLIED
    inherit          IDREFS #IMPLIED>
<!ELEMENT LexemeProperty (feat*)>
<!ELEMENT SyntacticArgument (feat*)>
<!ATTLIST SyntacticArgument
    id                 ID #IMPLIED
    target           IDREF #IMPLIED>
<!ELEMENT SubcategorizationFrameSet (feat*, SynArgMap*)>
<!ATTLIST SubcategorizationFrameSet
    id					ID #IMPLIED
    subcategorizationFrames	IDREFS #IMPLIED
    inherit				IDREFS #IMPLIED>
<!ELEMENT SynArgMap (feat*)>
<!ATTLIST SynArgMap
    arg1	IDREF #REQUIRED
    arg2	IDREF #REQUIRED>
            <!--#################### Package for Semantics -->
<!ELEMENT PredicativeRepresentation (feat*)>
<!ATTLIST PredicativeRepresentation
   predicate              IDREF #REQUIRED
   correspondences IDREFS #REQUIRED>
<!ELEMENT SemanticPredicate (feat*, Definition*, SemanticArgument*, PredicateRelation*)>
<!ATTLIST SemanticPredicate
    id                      ID #REQUIRED
    semanticTypes IDREFS #IMPLIED>
<!ELEMENT SemanticArgument (feat*, ArgumentRelation*)>
<!ATTLIST SemanticArgument
    id                      ID #IMPLIED
    semanticTypes IDREFS #IMPLIED>
<!ELEMENT ArgumentRelation (feat*)>
<!ATTLIST ArgumentRelation
    targets      IDREFS #IMPLIED>
<!ELEMENT SynSemCorrespondence (feat*,SynSemArgMap*)>
<!ATTLIST SynSemCorrespondence
    id              ID #REQUIRED>
<!ELEMENT SynSemArgMap (feat*)>
<!ELEMENT PredicateRelation (feat*)>
<!ATTLIST PredicateRelation
    targets          IDREFS #IMPLIED>
<!ELEMENT SenseExample (feat*)>
<!ATTLIST SenseExample
    id               ID #IMPLIED>
<!ELEMENT Synset (feat*, Definition*, SynsetRelation*, MonolingualExternalRef*)>
<!ATTLIST Synset
    id               ID #IMPLIED>
<!ELEMENT SynsetRelation (feat*)>
<!ATTLIST SynsetRelation
    targets      IDREFS #IMPLIED>
<!ELEMENT MonolingualExternalRef (feat*)>
<!ELEMENT SenseRelation (feat*)>
<!ATTLIST SenseRelation
    targets  IDREFS #REQUIRED>
            <!--#################### Package for Multilingual notations -->
<!ELEMENT SenseAxis (feat*, SenseAxisRelation*, InterlingualExternalRef*)>
<!ATTLIST SenseAxis
    id		ID #IMPLIED
    senses	IDREFS #IMPLIED
    synsets	IDREFS #IMPLIED>
<!ELEMENT InterlingualExternalRef (feat*)>
<!ELEMENT SenseAxisRelation (feat*)>
<!ATTLIST SenseAxisRelation
    targets          IDREFS #REQUIRED>
<!ELEMENT TransferAxis (feat*, TransferAxisRelation*, SourceTest*, TargetTest*)>
<!ATTLIST TransferAxis
    id               ID #IMPLIED
    syntacticBehaviours IDREFS #IMPLIED>
<!ELEMENT TransferAxisRelation (feat*)>
<!ATTLIST TransferAxisRelation
    targets          IDREFS #REQUIRED>
<!ELEMENT SourceTest (feat*)>
<!ATTLIST SourceTest
    syntacticBehaviours IDREFS #REQUIRED>
<!ELEMENT TargetTest (feat*)>
<!ATTLIST TargetTest
    syntacticBehaviours IDREFS #REQUIRED>
<!ELEMENT ContextAxis (feat*, ContextAxisRelation*)>
<!ATTLIST ContextAxis
    id               ID #IMPLIED
    examples  IDREFS #IMPLIED>
<!ELEMENT ContextAxisRelation (feat*)>
<!ATTLIST ContextAxisRelation
    targets          IDREFS #REQUIRED>
            <!--#################### Package for morphological patterns -->
<!ELEMENT MorphologicalPattern (feat*, TransformSet*, TransformCategory*, Affix*, AffixSlot*, AffixTemplate*)>
<!ATTLIST MorphologicalPattern
    id       ID #IMPLIED>
<!ELEMENT TransformSet (feat*, Process*, GrammaticalFeatures*, TransformCategory*)>
<!ELEMENT GrammaticalFeatures (feat*)>
<!ELEMENT Process (feat*, Condition*)>
<!ELEMENT Condition (feat*, GrammaticalFeatures*, TransformCategory*)>
<!ELEMENT Affix (feat*, AffixAllomorph*, GrammaticalFeatures*)>
<!ELEMENT AffixAllomorph (feat*, FormRepresentation*, Condition*)>
<!ELEMENT AffixTemplate (feat*, TemplateSlot*)>
<!ELEMENT TemplateSlot (feat*, Affix*)>
<!ATTLIST TemplateSlot
    affixslots IDREFS #IMPLIED>
<!ELEMENT AffixSlot (feat*)>
<!ATTLIST AffixSlot
    affixs IDREFS #IMPLIED>
<!ELEMENT TransformCategory (feat*)>
            <!--#################### Package for MWE patterns -->
<!ELEMENT MWEPattern (feat*, MWENode*)>
<!ATTLIST MWEPattern
    id       ID #REQUIRED>
<!ELEMENT MWENode (feat*, MWEEdge*, MWELex)>
<!ELEMENT MWEEdge (feat*, MWENode*)>
<!ELEMENT MWELex (feat*)>
            <!--#################### Package for Constraint expression -->
<!ELEMENT ConstraintSet (feat*, Constraint*)>
<!ELEMENT Constraint (feat*, LogicalOperation*)>
<!ATTLIST Constraint
    id       ID #IMPLIED>
<!ELEMENT LogicalOperation (feat*, AttributeValuation*, Constraint*)>
<!ATTLIST LogicalOperation
   constraints  IDREFS #IMPLIED>
<!ELEMENT AttributeValuation (feat*)>
            <!--#################### for data category adornment: feat stands for feature-->
<!ELEMENT feat EMPTY>
            <!-- att=constant to be taken from the DataCategoryRegistry -->
            <!-- val=free string or constant to be taken from the DCR-->
<!ATTLIST feat
    att      CDATA #REQUIRED 
    val      CDATA #REQUIRED>

=== buret/pylmflib/doc/xml/na_example.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE LexicalResource SYSTEM "DTD_LMF_REV_16.dtd">
<LexicalResource dtdVersion="16">
    <GlobalInformation>
        <feat att="languageCode" dcr:datcat="http://www.isocat.org/datcat/DC-2008" val="ISO-639-3"/>
    </GlobalInformation>
    <Speaker speakerId="F4" dcr:datcat="http://www.isocat.org/datcat/DC-3597"/>
    <Speaker speakerId="F5"/>
    <Speaker speakerId="M21"/>
    <Lexicon>
        <LexicalEntry id="æ_1" dcr:datcat="http://www.isocat.org/datcat/DC-6196">
            <feat att="partOfSpeech" dcr:datcat="http://www.isocat.org/datcat/DC-3748" val="noun" dcr:datcat="http://www.isocat.org/datcat/DC-1333"/>
            <feat att="date" dcr:datcat="http://www.isocat.org/datcat/DC-3694" val="2014-06-15"/>
            <Lemma targets="F4">
                <feat att="lexeme" dcr:datcat="http://www.isocat.org/datcat/DC-3723" val="æ˩˧"/>
            </Lemma>
            <Audio>
                <feat att="externalReference" dcr:datcat="http://www.isocat.org/datcat/DC-1975" val="B:1789"/>
            </Audio>
            <Audio>
                <feat att="externalReference" val="2011:2642"/>
            </Audio>
            <FormRepresentation targets="F5">
                <feat att="variantForm" dcr:datcat="http://www.isocat.org/datcat/DC-3768" val="æ˩˧"/>
            </FormRepresentation>
            <FormRepresentation targets="M21">
                <feat att="variantForm" val="æ˩˧"/>
            </FormRepresentation>
            <Sense id="æ_1-0" dcr:datcat="http://www.isocat.org/datcat/DC-1845">
                <SubjectField>
                    <feat att="language" dcr:datcat="http://www.isocat.org/datcat/DC-2482" val="fra"/>
                    <feat att="semanticDomain" dcr:datcat="http://www.isocat.org/datcat/DC-3755" val="animal"/>
                </SubjectField>
                <SubjectField>
                    <feat att="language" val="eng"/>
                    <feat att="semanticDomain" val="animal"/>
                </SubjectField>
                <Definition>    
                    <Statement>
                        <feat att="noteType" dcr:datcat="http://www.isocat.org/datcat/DC-6178" val="phonology"/>
                        <feat att="language" dcr:datcat="http://www.isocat.org/datcat/DC-2482" val="fra"/>
                        <feat att="note" dcr:datcat="http://www.isocat.org/datcat/DC-382" val="LM confirmé type "porc""/>
                    </Statement>
                    <Statement>
                        <feat att="noteType" val="tone"/>
                        <feat att="note" val="LM"/>
                    </Statement>
                </Definition>
                <Definition>
                    <feat att="language" dcr:datcat="http://www.isocat.org/datcat/DC-2482" val="eng"/>
                    <feat att="definition" dcr:datcat="http://www.isocat.org/datcat/DC-1972" val="chicken"/>
                    <feat att="gloss" dcr:datcat="http://www.isocat.org/datcat/DC-244" val="chicken"/>
                </Definition>
                <Definition>
                    <feat att="language" val="chn"/>
                    <feat att="definition" val="鸡"/>
                    <feat att="gloss" val="鸡"/>
                </Definition>
                <Definition>
                    <feat att="language" val="fra"/>
                    <feat att="definition" val="poulet, poule"/>
                    <feat att="gloss" val="poulet"/>
                </Definition>
                <Paradigm targets="mi1">
                    <feat att="paradigmLabel" dcr:datcat="http://www.isocat.org/datcat/DC-3741" val="classifier"/>
                    <feat att="paradigm" dcr:datcat="http://www.isocat.org/datcat/DC-3736" val="mi˩"/>
                </Paradigm>
                <Context>
                    <TextRepresentation>
                        <feat att="language" dcr:datcat="http://www.isocat.org/datcat/DC-2482" val="na?"/>
                        <feat att="writtenForm" dcr:datcat="http://www.isocat.org/datcat/DC-1836" val="æ˩ dzɯ˧-ze˩"/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="eng"/>
                        <feat att="writtenForm" val="...has eaten (a/some) chicken"/>                        
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="chn"/>
                        <feat att="writtenForm" val="吃了鸡"/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="fra"/>
                        <feat att="writtenForm" val="...a mangé (un/du) poulet"/>
                        <feat att="comment" dcr:datcat="http://www.isocat.org/datcat/DC-1846" val="PHONO"/>
                    </TextRepresentation>
                </Context>
                <Context>
                    <TextRepresentation>
                        <feat att="language" val="na?"/>
                        <feat att="writtenForm" val="æ˩ hwæ˧-ze˧"/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="eng"/>
                        <feat att="writtenForm" val="...has bought (a) chicken"/>                        
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="chn"/>
                        <feat att="writtenForm" val="买了鸡"/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="fra"/>
                        <feat att="writtenForm" val="...a acheté (un/du) poulet"/>
                        <feat att="comment" val="PHONO"/>
                    </TextRepresentation>
                </Context>
                <Context>
                    <TextRepresentation>
                        <feat att="language" val="na?"/>
                        <feat att="writtenForm" val="æ˩˥, | kʰv˧, | bo˩˥, | hwɤ˧˥, | ʝi˧, | lɑ˧, | tʰo˧li˧, | mv˧gv˧, | bv˧ʐv˧, | ʐwæ˧, | jo˧, | ʑi˩˥"/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="eng"/>
                        <feat att="writtenForm" val="the twelve years of the duodenary cycle"/>                        
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="chn"/>
                        <feat att="writtenForm" val="十二个生肖"/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="fra"/>
                        <feat att="writtenForm" val="les douze signes astrologiques"/>
                    </TextRepresentation>
                </Context>
            </Sense>
        </LexicalEntry>
        <LexicalEntry id="mi_1">
            <Lemma>
                <feat att="lexeme" val="mi˩"/>
            </Lemma>
        </LexicalEntry>
    </Lexicon>
</LexicalResource>

=== buret/pylmflib/doc/xml/japhug_example.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE LexicalResource SYSTEM "DTD_LMF_REV_16.dtd">
<LexicalResource dtdVersion="16">
    <GlobalInformation>
        <feat att="languageCode" val="ISO-639-3"/>
    </GlobalInformation>
    <Lexicon>
        <LexicalEntry id="akarɯ_1">
            <feat att="partOfSpeech" val="noun"/>
            <feat att="bibliography" dcr:datcat="http://www.isocat.org/datcat/DC-3687" val="plante"/>
            <feat att="date" val="2014-07-03"/>
            <Lemma>
                <feat att="lexeme" val="akarɯ"/>
            </Lemma>
            <Sense id="akarɯ_1-0">
                <Definition>
                    <feat att="language" val="eng"/>
                    <feat att="gloss" val="origan"/>
                </Definition>
                <Definition>
                    <feat att="language" val="chn"/>
                    <feat att="gloss" val="牛至"/>
                </Definition>
                <Context>
                    <TextRepresentation>
                        <feat att="language" val="jya"/>
                        <feat att="writtenForm" val="akarɯ nɯ sɯjno kɯ-xtɕi ci ŋu, ɯ-ru kɯ-xtshɯ-xtshɯm kɯ-ɣɯrni ci ŋu, ʁnɯ-tɣa jamar ma mɤ-mbro, ɯ-jwaʁ kɯ-ɤrtɯm, kɯ-rɲɟi tsa ci ŋu, ɯ-di mnɤm, ɯ-mɯntoʁ kɯ-ɣɯrni ŋgɯ kɯ-wɣrum tsa ci ŋu, ɯ-zrɤm kɯ-xtɕɯ-xtɕi ma me, ɯʑo smɤn ɯ-ŋgɯ kɤ-lɤt ɲɯ-sna."/>
                    </TextRepresentation>
                    <TextRepresentation>
                        <feat att="language" val="chn"/>
                        <feat att="writtenForm" val="牛至是一种小植物，茎非常细，呈红色，只有两乍高，有椭圆形的小叶，花是红里透白，有香味，只有小小的根。可以放在药里。"/>
                    </TextRepresentation>
                </Context>
           </Sense>
        </LexicalEntry>
    </Lexicon>
</LexicalResource>
